%%{init: {'themeVariables': {}}}%%

%%  
%% This details what diagram is about
%%

graph LR

  %% node definition section

  %% relationship definition section

%% class def at the bottom adds a transparecy to the nodes
classDef tr fill:#00000000, stroke:#00000000;